import type { FeatureFlags } from '../SettingsPage'
import { SETTINGS_STORAGE_KEY } from '../settingsKey'

/**
 * Sub-features: every feature exposes 2+ finer options in Settings. They are
 * stored as `sub["feature.option"]`; a missing entry means "on", so new
 * options appear enabled without migrating anyone's saved settings.
 */
export type SubFeature = {
  id: string
  title: string
  description: string
  /** Works even when its feature's main switch is off (shown as such in Settings). */
  independent?: boolean
}

export const subFeatures: Record<keyof FeatureFlags, SubFeature[]> = {
  dailySpin: [
    { id: 'dashboard', title: 'Show on dashboard', description: 'The spin card appears on Today.' },
    { id: 'jackpotFountain', title: 'Jackpot fountain', description: 'Gold burst when a car is won.' },
    { id: 'odds', title: 'Odds note', description: 'Shows the jackpot odds and reset time.' },
    { id: 'collectionLink', title: 'Collection link', description: 'Jump to your cars after a spin.' },
    { id: 'machineGlow', title: 'Machine glow', description: 'Animated lights on the spin machine.' },
  ],
  collectibles: [
    { id: 'focusCompanion', title: 'Focus companion', description: 'Your chosen car rides along in focus sessions.' },
    { id: 'carEffects', title: 'Car effects', description: 'Bounces, dashes and sparkles on car cards.' },
    { id: 'numbering', title: 'Card numbers', description: '“01 / 06” labels on cards.' },
    { id: 'lockedCars', title: 'Show locked cars', description: 'Silhouettes of cars still to find.' },
    { id: 'filterTabs', title: 'Filter tabs', description: 'All / Unlocked / Garage tabs.' },
  ],
  fullCalendar: [
    { id: 'fullscreen', title: 'Full-screen mode', description: 'A button to fill the whole screen.' },
    { id: 'capacity', title: 'Daily capacity bar', description: 'Hours available vs. blocked.' },
    { id: 'taskTray', title: 'Task tray', description: 'Drag unscheduled tasks onto the calendar.' },
    { id: 'weekends', title: 'Weekends', description: 'Show Saturday and Sunday.' },
    { id: 'nowLine', title: 'Now line', description: 'A line at the current time.' },
    { id: 'agenda', title: 'Agenda view', description: 'A list view of the week.' },
  ],
  visionBoard: [
    { id: 'badgeNodes', title: 'Badge nodes', description: 'Earned boss badges can be pinned to the board.' },
    { id: 'minimap', title: 'Minimap', description: 'Overview map in the corner.' },
    { id: 'grid', title: 'Dot grid', description: 'Background dots.' },
    { id: 'controls', title: 'Zoom controls', description: 'On-canvas zoom buttons.' },
    { id: 'snap', title: 'Snap to grid', description: 'Items align to a 20 px grid.' },
    { id: 'connect', title: 'Arrows', description: 'Connect cards with labelled arrows.' },
    { id: 'flowingArrows', title: 'Flowing arrows', description: 'Arrows animate in the direction they point.' },
    { id: 'whiteboardCards', title: 'Goals, habits & images', description: 'Pin long-term goals, live habits and pictures.' },
    { id: 'popIn', title: 'Pop-in notes', description: 'Notes and goals pop onto the board one by one when it opens.' },
  ],
  bloomWorld: [
    { id: 'avatar', title: 'Avatar and shop decor', description: 'Your avatar and items bought with petals.' },
    { id: 'dayNight', title: 'Day and night sky', description: 'Lighting follows your local time.' },
    { id: 'futurePeek', title: 'Peek at the future', description: 'Preview a fully grown island.' },
    { id: 'clouds', title: 'Drifting clouds', description: 'Clouds float over the island.' },
    { id: 'decorations', title: 'Milestone decorations', description: 'Lanterns, pond, windmill and more.' },
    { id: 'districtCards', title: 'District cards', description: 'Progress cards under the island.' },
    { id: 'growthNote', title: '“While you were away”', description: 'What grew since your last visit.' },
  ],
  breathe: [
    { id: 'customPattern', title: 'Custom pattern builder', description: 'Design your own rhythm.' },
    { id: 'soundCue', title: 'Sound cue', description: 'Soft tone on each phase.' },
    { id: 'vibrate', title: 'Vibration cue', description: 'Short buzz on each phase (phones).' },
    { id: 'rounds', title: 'Round goals', description: 'Choose 4, 8 or 12 rounds.' },
    { id: 'orbPulse', title: 'Orb animation', description: 'The orb grows and shrinks.' },
    { id: 'cycleCount', title: 'Round counter', description: 'Rounds completed.' },
  ],
  moodCheckin: [
    { id: 'detailed', title: 'Detailed mode', description: 'Emotion wheel and energy level.' },
    { id: 'wordCloud', title: 'Emotion word cloud', description: 'Words you use most.' },
    { id: 'recent', title: 'Recent check-ins slider', description: 'Your latest entries.' },
    { id: 'notes', title: 'Notes', description: 'A word about why.' },
    { id: 'weekChart', title: 'Week chart', description: 'Your last seven days.' },
    { id: 'oneTapLog', title: 'One-tap logging', description: 'A single tap saves your mood.' },
    { id: 'factorSwipe', title: 'Why this mood?', description: 'Swipe through sleep, food, movement and more.' },
    { id: 'nextStep', title: 'Suggested next step', description: 'Links to a feature that suits your mood.' },
    { id: 'crossFeature', title: 'Moods across Bloom', description: 'Timeline of moods tagged on other pages.' },
    { id: 'marbleJar', title: 'Mood marble jar', description: 'Every check-in drops into a jar as a marble (physics).' },
  ],
  gratitude: [
    { id: 'customJars', title: 'Custom jars', description: 'Create your own jars.' },
    { id: 'shake', title: 'Shake for a memory', description: 'Resurface a random note.' },
    { id: 'compare', title: 'Compare jars', description: 'See which jar is fullest.' },
    { id: 'notes', title: 'Notes slider', description: 'Browse notes in the jar.' },
    { id: 'counts', title: 'Jar counts', description: 'Numbers under each jar.' },
    { id: 'promptSwipe', title: 'Swipe prompts', description: 'Swipe right on a prompt to answer it in one line.' },
    { id: 'moodPrompts', title: 'Mood-aware prompts', description: 'Gentle prompts first on hard days.' },
    { id: 'noteDrop', title: 'Note drop', description: 'A note tumbles into the jar when saved.' },
    { id: 'letterWall', title: 'Letter wall', description: 'Notes pinned as envelopes on a cork board; open one to read it.' },
  ],
  compactMode: [
    { id: 'sidebar', title: 'Compact sidebar', description: 'Tighter navigation rows.' },
    { id: 'cards', title: 'Compact cards', description: 'Less padding inside cards.' },
    { id: 'hero', title: 'Compact headers', description: 'Smaller page and hero headers.' },
    { id: 'type', title: 'Smaller headings', description: 'Tighter type scale.' },
    { id: 'descriptions', title: 'Hide descriptions', description: 'Only titles on cards.' },
  ],
  sleepTracker: [
    { id: 'windDown', title: 'Wind-down routine', description: 'Bedtime countdown and checklist.' },
    { id: 'insights', title: 'Sleep insights', description: 'Charts and factor impact.' },
    { id: 'factors', title: 'Factor tags', description: 'Tag caffeine, screens, exercise…' },
    { id: 'debt', title: 'Sleep debt', description: 'Hours short of your goal.' },
    { id: 'consistency', title: 'Consistency score', description: 'How regular your bedtime is.' },
    { id: 'history', title: 'Recent nights list', description: 'Edit or delete recent nights.' },
    { id: 'morningCheckin', title: 'Morning check-in', description: 'Log last night with one tap on how you woke up.' },
    { id: 'factorSwipe', title: 'Swipe sleep factors', description: 'Yes/no on caffeine, screens, stress…' },
    { id: 'sunrise', title: 'Sunrise scene', description: 'Animated dawn and today’s sunrise time.' },
    { id: 'smartDefaults', title: 'Smart times', description: 'Uses your bedtime and the time you tap.' },
  ],
  petalShop: [
    { id: 'wearables', title: 'Avatar items', description: 'Hats, outfits and pets.' },
    { id: 'decor', title: 'World decor', description: 'Decorations for Bloom World.' },
    { id: 'garageItems', title: 'Garage upgrades', description: 'Upgrades for your car garage.' },
    { id: 'avatarPreview', title: 'Avatar preview', description: 'See your avatar in the shop.' },
    { id: 'toast', title: 'Purchase toast', description: '“It’s yours!” message.' },
    { id: 'wishSwipe', title: 'Swipe wishlist', description: 'Swipe right on items you want.' },
    { id: 'wishRings', title: 'Savings rings', description: 'Animated progress rings toward each wish.' },
    { id: 'affordEta', title: 'Days to afford', description: 'Estimate from your average petals a day.' },
    { id: 'flipBalance', title: 'Flip-counter balance', description: 'Animated petal counter.' },
    { id: 'shopWindow', title: 'Shop window', description: 'A storybook shop front with shelves, swinging price tags and a waving shopkeeper.' },
  ],
  reminders: [
    { id: 'system', title: 'System notifications', description: 'Notify when Bloom is in the background.' },
    { id: 'bellAnimation', title: 'Ringing bell', description: 'Active bells ring now and then.' },
    { id: 'habits', title: 'Habit reminders', description: 'Bells on habit cards.' },
    { id: 'routines', title: 'Routine reminders', description: 'Bells on routine cards.' },
    { id: 'quickDone', title: 'One-tap done', description: 'Mark a habit done from the reminder.' },
  ],
  adaptiveGoals: [
    { id: 'stretch', title: 'Gentle stretch', description: 'Aim 10% above your pace (off = match it).' },
    { id: 'badge', title: '“Adapted” badge', description: 'Label goals that changed.' },
    { id: 'longHistory', title: 'Six-week memory', description: 'Use 6 weeks of history instead of 3.' },
    { id: 'extraGoals', title: 'Extra goals', description: 'Tasks, intentions, routines, sessions, active days.', independent: true },
    { id: 'floor', title: 'Keep a floor', description: 'Never go below half the default target.' },
    { id: 'summitTrail', title: 'Summit trail', description: 'Active challenges climb a mountain trail as you finish their steps.', independent: true },
  ],
  celebrations: [
    { id: 'checkins', title: 'Check-in bursts', description: 'Coins when you complete a habit.' },
    { id: 'milestones', title: 'Milestone fountains', description: 'Big bursts for streak milestones.' },
    { id: 'routines', title: 'Routine finishes', description: 'Stars when a routine is complete.' },
    { id: 'shop', title: 'Shop purchases', description: 'Stars when you buy something.' },
    { id: 'release', title: 'Burn & release', description: 'Sparks from the campfire.' },
    { id: 'yearbook', title: 'Year book', description: 'Stars when your book is ready.' },
  ],
  burnRelease: [
    { id: 'daybookShortcut', title: 'Daybook shortcut', description: 'From Fear Setting and Shadow Work pages.' },
    { id: 'flick', title: 'Flick to release', description: 'Throw the card with momentum.' },
    { id: 'smoke', title: 'Smoke', description: 'The card turns to smoke.' },
    { id: 'count', title: 'Release counter', description: 'How many thoughts you let go.' },
    { id: 'handwriting', title: 'Handwritten card', description: 'A handwriting font on the card.' },
    { id: 'ash', title: 'Words to ash', description: 'Your words crumble into ash letters that drift away.' },
  ],
  garage: [
    { id: 'upgrades', title: 'Garage upgrades', description: 'Neon, turntable, chargers and more.' },
    { id: 'turntable', title: 'Turntable spin', description: 'Pad 1 rotates your car.' },
    { id: 'neon', title: 'Neon sign', description: 'Show the neon sign if owned.' },
    { id: 'spotlights', title: 'Spotlights', description: 'Show spotlights if owned.' },
    { id: 'plants', title: 'Plants', description: 'Show plants if owned.' },
    { id: 'chargers', title: 'Chargers', description: 'Show charging stations if owned.' },
  ],
  urgeClock: [
    { id: 'seconds', title: 'Seconds', description: 'Tick every second.' },
    { id: 'highScore', title: 'High score', description: 'Best streak and “New best”.' },
    { id: 'progress', title: 'Progress to best', description: 'Bar toward your best streak.' },
    { id: 'resisted', title: 'Urges resisted', description: 'Urges logged this run.' },
    { id: 'glow', title: 'Record glow', description: 'Gold border when you beat your best.' },
  ],
  focusRoom: [
    { id: 'soundtrack', title: 'Soundtrack', description: 'Classical and cinematic music.' },
    { id: 'avatar', title: 'Avatar at the desk', description: 'Your avatar works with you.' },
    { id: 'nightSky', title: 'Day and night', description: 'The window follows the time of day.' },
    { id: 'notes', title: 'Music notes', description: 'Floating notes while working.' },
    { id: 'progress', title: 'Progress bar', description: 'Session progress along the floor.' },
  ],
  timeCapsule: [
    { id: 'onThisDay', title: 'On this day', description: 'Entries from a week, month or year ago.' },
    { id: 'gratitude', title: 'Gratitude fallback', description: 'A jar note when nothing else matches.' },
    { id: 'shuffle', title: 'Shuffle', description: 'Pick another memory.' },
    { id: 'greeting', title: 'Morning greeting', description: '“Good morning, from the past.”' },
    { id: 'fullText', title: 'Full text', description: 'Show the whole memory, not a preview.' },
  ],
  thoughtDiff: [
    { id: 'counts', title: 'Change counts', description: 'How many words are new or faded.' },
    { id: 'autoOpen', title: 'Open automatically', description: 'Show the comparison when a page opens.' },
    { id: 'removed', title: 'Show faded words', description: 'Struck-through words you no longer use.' },
    { id: 'added', title: 'Highlight new words', description: 'Green highlight for new thoughts.' },
    { id: 'date', title: 'Comparison date', description: 'Which page you are comparing with.' },
  ],
  queryBuilder: [
    { id: 'presets', title: 'Example questions', description: 'One-tap starting points.' },
    { id: 'moodAverage', title: 'Mood average', description: 'Average mood of the matches.' },
    { id: 'groups', title: 'Nested groups', description: 'Groups inside groups.' },
    { id: 'habitField', title: 'Habit field', description: 'Filter by habits done that day.' },
    { id: 'tagsField', title: 'Tag field', description: 'Filter by tags and emotions.' },
    { id: 'dateField', title: 'Date field', description: 'Filter by date.' },
  ],
  yearbook: [
    { id: 'coverPreview', title: 'Cover preview', description: '3D book cover preview.' },
    { id: 'stats', title: 'Stats preview', description: 'The year in numbers before printing.' },
    { id: 'daybookChapter', title: 'Daybook chapter', description: 'Offer the Daybook chapter.' },
    { id: 'journalChapter', title: 'Reflections chapter', description: 'Offer the journal chapter.' },
    { id: 'gratitudeChapter', title: 'Good things chapter', description: 'Offer the gratitude chapter.' },
  ],
  memoryPalace: [
    { id: 'inertia', title: 'Drag and scroll', description: 'Spin the ring with momentum.' },
    { id: 'monthMarkers', title: 'Month markers', description: 'Glowing dots at each month.' },
    { id: 'moodColors', title: 'Mood colours', description: 'Colour days by mood.' },
    { id: 'fog', title: 'Fog', description: 'Depth fog around the ring.' },
    { id: 'keyboard', title: 'Keyboard navigation', description: 'Arrow keys move between days.' },
    { id: 'zoom', title: 'Zoom on click', description: 'Clicking a day zooms in.' },
    { id: 'ribbon', title: 'Year ribbon', description: 'The whole year as one strip; click any day to spin there.' },
  ],
  skillConstellation: [
    { id: 'starfield', title: 'Starfield', description: 'Background stars.' },
    { id: 'statBranches', title: 'Stat branches', description: 'Strength, intelligence and spirit stars.' },
    { id: 'pulse', title: 'Star pulse', description: 'Lit stars gently pulse.' },
    { id: 'links', title: 'Constellation lines', description: 'Lines between stars.' },
    { id: 'flyTo', title: 'Camera flight', description: 'Fly to the star you click.' },
  ],
  streakJourney: [
    { id: 'monuments', title: 'Monuments', description: 'A monument every 7 days.' },
    { id: 'quotes', title: 'Journal quotes', description: 'What you wrote along the way.' },
    { id: 'trees', title: 'Trees', description: 'Trees along the path.' },
    { id: 'fog', title: 'Fog', description: 'Distance fog.' },
    { id: 'highlight', title: 'Active day highlight', description: 'Highlight the day in view.' },
  ],
  moodOrb: [
    { id: 'liquid', title: 'Liquid motion', description: 'The surface moves continuously.' },
    { id: 'colorShift', title: 'Colour shift', description: 'Colour follows your mood.' },
    { id: 'gloss', title: 'Glass shine', description: 'Specular highlights.' },
    { id: 'label', title: 'Mood label', description: 'Anxious … Calm label.' },
    { id: 'autoMood', title: 'Set mood from orb', description: 'The orb picks your 1–5 mood.' },
  ],
  placesMap: [
    { id: 'heat', title: 'Heat halos', description: 'Soft halos sized by visits.' },
    { id: 'offlineTiles', title: 'Offline map tiles', description: 'Cache tiles for offline use.' },
    { id: 'moodCapture', title: 'Save with mood check-ins', description: 'Location on each mood check-in.' },
    { id: 'daybookCapture', title: 'Save with Daybook pages', description: 'Location when a page is completed.' },
    { id: 'naming', title: 'Name places', description: 'Give places names.' },
    { id: 'insight', title: '“You feel best at…”', description: 'Your happiest place.' },
  ],
  urgeTracker: [
    { id: 'patterns', title: 'Patterns view', description: 'When and where urges happen.' },
    { id: 'context', title: 'Context capture', description: 'Time of day and session info.' },
    { id: 'intensity', title: 'Intensity step', description: 'Rate how strong the urge was.' },
    { id: 'manage', title: 'Manage habits', description: 'Add or archive urge habits.' },
    { id: 'contextCard', title: 'Context card', description: 'Explains what is captured.' },
    { id: 'surfWave', title: 'Urge-surfing wave', description: 'A 90-second animated wave to ride out an urge.' },
    { id: 'passedCheck', title: 'Did it pass?', description: 'Ask after the wave and count wins.' },
    { id: 'surfStats', title: 'Surf stats', description: 'How often urges passed.' },
    { id: 'alternatives', title: 'Swipe alternatives', description: 'Swipe right on something to do instead.' },
    { id: 'moodTag', title: 'What is under it?', description: 'One-tap mood; alternatives match it.' },
  ],
  habitTracker: [
    { id: 'library', title: 'Habit & routine library', description: 'Adopt ready-made cards.' },
    { id: 'routines', title: 'Routines', description: 'Timed step-by-step routines.' },
    { id: 'grid', title: 'Contribution grid', description: 'History heatmap on each habit.' },
    { id: 'streak', title: 'Streak footer', description: 'Current and best streak.' },
    { id: 'edit', title: 'Edit and delete', description: 'Actions on each card.' },
    { id: 'swipeCheckin', title: 'Swipe check-in', description: 'Swipe right on habits you did today.' },
    { id: 'moodTag', title: 'Guided mood', description: 'One-tap mood before checking in.' },
    { id: 'gentleMode', title: 'Gentle mode', description: 'Tired or low? Habits shrink to 2 minutes.' },
    { id: 'skipDay', title: 'Skip for today', description: 'Swipe left hides a habit until tomorrow.' },
    { id: 'allDoneBurst', title: 'All-done celebration', description: 'Stars when the last habit is checked.' },
    { id: 'doneList', title: 'Done today list', description: 'Animated list with undo.' },
    { id: 'stickerBook', title: 'Sticker book', description: 'A month page where every check-in is a sticker.' },
  ],
  chatJournal: [
    { id: 'quickEntry', title: 'Quick entry', description: 'Short journal entries with tags.' },
    { id: 'promptChips', title: 'Prompt chips', description: 'Suggested answers to get started.' },
    { id: 'ratings', title: 'Mood & energy ratings', description: 'Rate mood and energy.' },
    { id: 'modeSwitch', title: 'Mode switch', description: 'Choose quick or guided.' },
    { id: 'stepCounter', title: 'Step counter', description: 'Where you are in the guided flow.' },
    { id: 'moodStart', title: 'Start from a mood', description: 'One tap sets the session mood.' },
    { id: 'topicSwipe', title: 'Swipe topics', description: 'Swipe right on what is on your mind; they become tags.' },
    { id: 'toneMeter', title: 'Tone meter', description: 'Animated gauge of how your last reply reads.' },
    { id: 'storyCarousel', title: 'Story carousel', description: 'Past reflections as storybook cards in a 3D coverflow.' },
  ],
  rpgSkillTree: [
    { id: 'weeklyGoals', title: 'Weekly goals', description: 'Goal cards on the Growth panel.' },
    { id: 'notices', title: 'Reward notices', description: 'Pop-ups for XP and level-ups.' },
    { id: 'levelBar', title: 'Level bar', description: 'XP progress to the next level.' },
    { id: 'sound', title: 'Sound toggle', description: 'Turn reward sounds on or off.' },
    { id: 'skillsLink', title: 'Explore skills link', description: 'Shortcut to the skill tree.' },
    { id: 'livingSeedling', title: 'Living seedling', description: 'Grows from habits, focus, journals, tasks and moods.' },
    { id: 'seasons', title: 'Seasonal leaves', description: 'Leaf colours follow the season.' },
    { id: 'thirst', title: 'Thirst hint', description: 'Shows when no habit has watered it today.' },
    { id: 'feedLinks', title: 'Feed links', description: 'Each part links to the feature that feeds it.' },
  ],
  weeklyRaidBoss: [
    { id: 'hp', title: 'Boss health bar', description: 'Show the raid boss HP.' },
    { id: 'damage', title: 'Damage labels', description: 'Show how much each action hits.' },
    { id: 'bossMark', title: 'Boss emblem', description: 'The crown emblem.' },
    { id: 'levelTag', title: 'Boss level', description: 'The boss level tag.' },
    { id: 'attackNote', title: 'Attack feedback', description: 'Message after an attack.' },
  ],
  daybookModes: [
    { id: 'autosave', title: 'Autosave', description: 'Save pages as you type.' },
    { id: 'focusWriting', title: 'Focus writing', description: 'Hide everything but the page.' },
    { id: 'pages', title: 'Your pages slider', description: 'Recent pages on the Daybook home.' },
    { id: 'wordCount', title: 'Word count', description: 'Live word count.' },
    { id: 'extraTools', title: 'Extra formatting', description: 'Highlight, code, quote and divider.' },
    { id: 'search', title: 'Page search', description: 'Search pages by meaning.' },
    { id: 'ambient', title: 'Breathing glow', description: 'Calm animation on reflection pages.' },
    { id: 'lifeJournals', title: 'Life journals', description: 'Boundaries, connection, reading notes, clear writing, work shutdown and meeting prep.' },
    { id: 'assist', title: 'Page helpers', description: 'Small tools under each page.' },
    { id: 'wordGoal', title: 'Word goal ring', description: 'A ring that fills toward your word goal.' },
    { id: 'readingTime', title: 'Reading time', description: 'How long the page takes to read.' },
    { id: 'writingCoach', title: 'Clear-writing coach', description: 'Long sentences, adverbs and passive voice on Clear writing pages.' },
    { id: 'meetingExport', title: 'Meeting to calendar', description: 'Export Meeting prep pages as a calendar event.' },
    { id: 'flourish', title: 'Ink flourish', description: 'A hand-drawn line inks itself under each title.' },
    { id: 'moodPicks', title: 'Mood picks', description: 'Tap a mood; swipe through journals that suit it.' },
    { id: 'timePicks', title: 'Time-of-day picks', description: 'Morning, afternoon or evening journals.' },
    { id: 'typedSpark', title: 'Typed spark', description: 'A question types itself out to beat the blank page.' },
    { id: 'bookshelf', title: 'Bookshelf', description: 'Each journal type becomes a floating 3D storybook.' },
    { id: 'bookFaces', title: 'Book faces', description: 'Covers with blinking faces.' },
    { id: 'bookFloat', title: 'Floating books', description: 'Books bob gently and tilt toward your pointer.' },
  ],
  languageSelector: [
    { id: 'dialects', title: 'Fun dialects', description: 'Pirate and slang English.' },
    { id: 'french', title: 'French', description: 'Français.' },
    { id: 'icon', title: 'Language icon', description: 'Icon on the picker.' },
    { id: 'nativeNames', title: 'Native names', description: '“Français” instead of “French”.' },
  ],
  walkthroughTour: [
    { id: 'wizard', title: 'Pixel wizard narrator', description: 'The wizard in guide pop-ups.', independent: true },
    { id: 'reveal', title: 'Animated text', description: 'Words reveal one by one.', independent: true },
    { id: 'progress', title: 'Step progress', description: '“2 / 5” in guides.' },
    { id: 'back', title: 'Back button', description: 'Go to the previous step.' },
    { id: 'dim', title: 'Dim the page', description: 'Darken everything but the highlight.', independent: true },
  ],
  timeSince: [
    { id: 'splitFlap', title: 'Split-flap digits', description: 'Train-station flip animation.' },
    { id: 'countdowns', title: 'Countdowns', description: 'Count down to future events.' },
    { id: 'urgeLink', title: 'Urge clocks on dashboard', description: 'Time since your last slip.' },
    { id: 'withBloom', title: '“With Bloom” counter', description: 'Time since you started.' },
    { id: 'units', title: 'Unit labels', description: 'DAYS / HRS / MIN / SEC.' },
    { id: 'custom', title: 'Your own counters', description: 'Add counters of your own.' },
  ],
  drawnAchievements: [
    { id: 'skills', title: 'Skill unlocks', description: 'Drawn illustration when a skill unlocks.' },
    { id: 'levels', title: 'Level-ups', description: 'Drawn illustration on each new level.' },
    { id: 'streaks', title: 'Streak milestones', description: 'Drawn tree at 7/30/100-day streaks.' },
    { id: 'fill', title: 'Colour fill', description: 'Colour floods in after the drawing.' },
    { id: 'autoClose', title: 'Close by itself', description: 'Disappears after a few seconds.' },
  ],
  flowTopography: [
    { id: 'live', title: 'Live mountain', description: 'Your flow range grows as you type.' },
    { id: 'save', title: 'Save fingerprint', description: 'Keep the range with the page.' },
    { id: 'fingerprint', title: 'Show on open', description: 'The saved range at the top of the page.' },
    { id: 'thumbnails', title: 'Page thumbnails', description: 'Tiny ranges on “Your pages” cards.' },
    { id: 'ravines', title: 'Ravines', description: 'Backspacing carves jagged ravines.' },
    { id: 'stats', title: 'WPM and flow %', description: 'Typing speed and time in flow.' },
  ],
  impactTasks: [
    { id: 'shatter', title: 'Shatter on impact', description: 'Hard wall hits break the task into debris.' },
    { id: 'bonusExp', title: 'Bonus EXP', description: 'Shattering grants extra EXP by weight.' },
    { id: 'shake', title: 'Screen shake', description: 'A little rumble when it shatters.' },
    { id: 'hint', title: 'How-to hint', description: '“Grab it and throw it…”' },
    { id: 'heavyOnly', title: 'Heavy tasks only', description: 'Off: every completed task falls.' },
  ],
  dietTracker: [
    { id: 'macros', title: 'Macros', description: 'Protein, carbs and fat alongside calories.' },
    { id: 'water', title: 'Water glasses', description: 'Tap glasses to track water.' },
    { id: 'library', title: 'Quick-add foods', description: 'One tap for common meals.' },
    { id: 'mindful', title: 'Mindful eating', description: 'Hunger before, fullness and energy after.' },
    { id: 'insights', title: 'Gentle insights', description: 'Patterns like late meals or sluggish foods.' },
    { id: 'swipeFoods', title: 'Swipe meals', description: 'Swipe right on foods that fit this meal time.' },
    { id: 'quickWater', title: 'One-tap water', description: 'A big +1 glass button.' },
    { id: 'afterFeeling', title: 'How it left you', description: 'Tap how you feel after eating; insights learn from it.' },
  ],
  monkMode: [
    { id: 'sand', title: 'Sand (not smoke)', description: 'Words crumble and fall as sand. Off: they drift up as smoke.' },
    { id: 'zen', title: 'Full screen', description: 'Everything else fades away.' },
    { id: 'mandala', title: 'Mandala', description: 'A slowly turning mandala behind the words.' },
    { id: 'bell', title: 'Opening bell', description: 'A soft chime when you begin.' },
    { id: 'quick', title: 'Crumble after 10 s', description: 'Off: words linger for 20 seconds.' },
  ],
  energySankey: [
    { id: 'manualLog', title: 'Log hours', description: 'Add leisure, scrolling, exercise and more by hand.' },
    { id: 'burnout', title: 'Burnout flow', description: 'Show drains and sleep debt feeding burnout.' },
    { id: 'gradient', title: 'Gradient links', description: 'Links blend from source to target colour.' },
    { id: 'range', title: '30-day view', description: 'Switch between this week and a month.' },
    { id: 'insights', title: 'Debug your week', description: 'Plain-language observations.' },
  ],
  voiceMemos: [
    { id: 'liveMeter', title: 'Live levels', description: 'Animated bars while recording.' },
    { id: 'waveform', title: 'Waveform', description: 'Scrub a waveform during playback.' },
    { id: 'transcribe', title: 'On-device transcription', description: 'Whisper runs in your browser.' },
    { id: 'extract', title: 'Key points & ideas', description: 'Bullets, habit ideas and mood tags.' },
    { id: 'toDaybook', title: 'Send to Daybook', description: 'Open the transcript as a Daybook page.' },
    { id: 'soundLab', title: 'Sound Lab', description: 'Remove noise, level the voice and trim silences.' },
    { id: 'spectrogram3d', title: '3D spectrogram', description: 'A spectral mountain of the recording.' },
    { id: 'openFile', title: 'Open audio files', description: 'Bring in .wav, .m4a or .webm from disk.' },
  ],
  insightsLab: [
    { id: 'findings', title: 'Top findings', description: 'The strongest relationships in plain words.' },
    { id: 'heatmap', title: 'Correlation heatmap', description: 'Every metric against every other.' },
    { id: 'scatter', title: 'Scatter plot', description: 'See the days behind a correlation.' },
    { id: 'regression', title: 'Trend line', description: 'Linear regression through the points.' },
    { id: 'pdfBook', title: 'PDF report', description: 'A print-ready summary.' },
    { id: 'zipBackup', title: 'Zip backup', description: 'All data, pages and recordings in one file.' },
  ],
  smartSearch: [
    { id: 'instantKeyword', title: 'Instant keyword results', description: 'Find pages before the AI model loads.' },
    { id: 'hybrid', title: 'Hybrid ranking', description: 'Blend meaning with exact words.' },
    { id: 'autoTags', title: 'Auto-tags', description: 'Themes like #work or #sleep on results.' },
    { id: 'tagCloud', title: 'Theme cloud', description: 'Tap a theme to search it.' },
    { id: 'related', title: 'Related while writing', description: 'Earlier pages on the same topic.' },
  ],
  omnibox: [
    { id: 'habits', title: 'Log habits', description: '> habit read' },
    { id: 'tasks', title: 'Add tasks', description: '> task call mum' },
    { id: 'nourish', title: 'Water and meals', description: '> water 2, > meal pasta 550' },
    { id: 'themes', title: 'Themes and mood', description: '> theme dracula, > mood 4' },
    { id: 'previews', title: 'Entry previews', description: 'Read a journal entry before opening it.' },
  ],
  pixelJuice: [
    { id: 'sprites', title: 'Pixel loot', description: 'A sword, potion, gem… pops from your tick.' },
    { id: 'sound', title: 'Chiptune sounds', description: 'A coin blip, or a level-up arpeggio.' },
    { id: 'sparks', title: 'Pixel sparks', description: 'Square confetti bursts.' },
    { id: 'chest', title: 'Treasure chest', description: 'Streak milestones open a chest.' },
    { id: 'parallax', title: 'Loot shelf', description: 'Today’s loot on the Habits page, tilting with your cursor.' },
  ],
  microNutrients: [
    { id: 'radar', title: 'Radar chart', description: 'Eight nutrient groups against targets.' },
    { id: 'table', title: 'All nutrients', description: 'Thirteen vitamins and minerals with bars.' },
    { id: 'diversity', title: 'Gut diversity', description: 'Count different plants toward 30 a week.' },
    { id: 'hydratedBuff', title: 'Hydrated buff', description: 'Electrolytes + water grants +5 HP stamina.' },
    { id: 'usda', title: 'USDA food table', description: 'Offline ingredient data stored on this device.' },
  ],
  recipeBuilder: [
    { id: 'cookLoss', title: 'Cook loss', description: 'Account for moisture lost or water absorbed in cooking.' },
    { id: 'units', title: 'Kitchen units', description: '“1 1/2 tbsp”, cups and ounces become grams.' },
    { id: 'macroBar', title: 'Macro split', description: 'Protein, carbs and fat per serving.' },
    { id: 'saveRecipes', title: 'Saved recipes', description: 'Keep recipes and log a serving in one tap.' },
    { id: 'scale', title: 'Kitchen scale', description: 'Needle springs to the total weight.' },
  ],
  breathSilk: [
    { id: 'mic', title: 'Listen to my breath', description: 'Breath sounds drive the silk (on-device).' },
    { id: 'ripple', title: 'Water ripples', description: 'Rings spread across the silk with each breath.' },
    { id: 'breathePage', title: 'On the Breathe page', description: 'A biofeedback card above the techniques.' },
    { id: 'elementColours', title: 'Element colours', description: 'The silk takes the colour of the chosen element.' },
    { id: 'pacer', title: 'Pacer fallback', description: 'Follows a gentle 4-in, 6-out rhythm without the mic.' },
  ],
  wuXing: [
    { id: 'stanceCamera', title: 'Stance camera', description: 'Pose detection measures how grounded you are.' },
    { id: 'bass', title: 'Grounding bass', description: 'A drone that deepens as you sink.' },
    { id: 'chimes', title: 'Bowls & chimes', description: 'Generative pentatonic strikes.' },
    { id: 'skeleton', title: 'Skeleton overlay', description: 'See the tracked pose over the preview.' },
    { id: 'breathDensity', title: 'Breath density', description: 'Chimes thicken as you inhale.' },
  ],
  exerciseGuides: [
    { id: 'wheelchair', title: 'Wheelchair mode control', description: 'Show the switch for supported seated movements.' },
    { id: "animation", title: "Animated form guide", description: "The figure moves through each rep." },
    { id: "muscleMap", title: "Muscle map", description: "Front and back maps of what works." },
    { id: "cues", title: "Form cues", description: "Short checklist for good form." },
    { id: "mistakes", title: "Common mistakes", description: "What to avoid." },
    { id: "tempo", title: "Tempo & metronome", description: "Clicks for lowering and lifting." },
    { id: "slowMo", title: "Slow motion", description: "Speed slider to study the movement." },
    { id: "mirror", title: "Mirror view", description: "Flip the figure to match you." },
    { id: "filters", title: "Filters", description: "By muscle, equipment and level." },
    { id: "favourites", title: "Favourites", description: "Star the moves you like." },
    { id: "voice", title: "Voice coach", description: "Counts reps and calls cues aloud." },
    { id: 'moreMoves', title: 'Neck, face, arm and hand moves', description: 'Small-joint moves, standing and seated.' },
    { id: 'areaFilter', title: 'Body-area filter', description: 'Neck, face, shoulders, arms, hands, core, legs.' },
    { id: 'positionFilter', title: 'Position filter', description: 'Standing, seated or floor.' },
    { id: 'programs', title: 'Goal programs', description: 'Exercise combinations for a body goal.' },
    { id: 'rest', title: 'Rest timer', description: 'Countdown between moves in a program.' },
    { id: 'autoAdvance', title: 'Auto-advance', description: 'Move on when the target is reached.' },
    { id: 'difficulty', title: 'Program difficulty', description: 'Easy, normal or hard rep targets.' },
    { id: 'printPlan', title: 'Printable plan', description: 'Print a program to take with you.' },
    { id: 'seatedFigure', title: 'Wheelchair on the figure', description: 'Draw the chair under seated moves.' },
    { id: 'faceHands', title: 'Face and hand detail', description: 'Animated mouth and fingers on the figure.' },
  ],
  workoutLog: [
    { id: "templates", title: "Templates", description: "Push, pull, legs, full body and home." },
    { id: "restTimer", title: "Rest timer", description: "Counts down after every set." },
    { id: "rpe", title: "Effort (RPE)", description: "Rate how hard each set felt." },
    { id: "prs", title: "Personal records", description: "Celebrate new bests as they happen." },
    { id: "e1rm", title: "Estimated max", description: "Epley one-rep max for each set." },
    { id: "volumeChart", title: "Volume chart", description: "Total kilograms per workout." },
    { id: "progressChart", title: "Progress chart", description: "Your estimated max over time." },
    { id: "plates", title: "Plate calculator", description: "Which plates go on the bar." },
    { id: "muscleVolume", title: "Weekly muscle sets", description: "Hard sets per muscle this week." },
    { id: "history", title: "History", description: "Every workout you have logged." },
    { id: 'weekBars', title: 'Week plates', description: 'This week’s volume as stacked plates that drop in.' },
  ],
  intervalCoach: [
    { id: "presets", title: "Programs", description: "Tabata, HIIT, EMOM, sprints and gentle." },
    { id: "builder", title: "Custom builder", description: "Sliders for work, rest and rounds." },
    { id: "voice", title: "Voice cues", description: "Work, rest and halfway, spoken." },
    { id: "beeps", title: "Beeps", description: "Tones at changes and a 3-2-1 countdown." },
    { id: "ring", title: "Progress ring", description: "A glowing ring drains each interval." },
    { id: "warmCool", title: "Warm-up & cool-down", description: "Easy minutes before and after." },
    { id: "rounds", title: "Round counter", description: "Round 3 of 8." },
    { id: "c25k", title: "Couch to 5K", description: "A nine-week run/walk plan that remembers where you are." },
    { id: "calories", title: "Calorie estimate", description: "From effort and your weight." },
    { id: "logWorkouts", title: "Log to workouts", description: "Finished sessions appear in your workout history." },
  ],
  yogaFlow: [
    { id: "library", title: "Pose library", description: "Twelve poses to study." },
    { id: "builder", title: "Flow builder", description: "Drag and drop poses into your own flow." },
    { id: "player", title: "Guided player", description: "The figure morphs from pose to pose." },
    { id: "breathCue", title: "Breath cue", description: "A glowing orb paces each breath." },
    { id: "sanskrit", title: "Sanskrit names", description: "Traditional names beside each pose." },
    { id: "presets", title: "Preset flows", description: "Sun salutation, energiser, balance, wind-down." },
    { id: "savedFlows", title: "Saved flows", description: "Keep the flows you build." },
    { id: "voice", title: "Voice guidance", description: "Hear each pose and its cue." },
    { id: "timeline", title: "Flow timeline", description: "See where you are in the sequence." },
    { id: "benefits", title: "Benefits", description: "Why each pose helps." },
    { id: 'lotus', title: 'Lotus breath', description: 'A lotus opens and closes with your breath behind the pose.' },
  ],
  mobility: [
    { id: "bodyMap", title: "Body map", description: "Tap where it feels tight." },
    { id: "routines", title: "Routines", description: "Desk reset, morning, runner, low back, full body." },
    { id: "circleTimer", title: "Circle timer", description: "A colour-shifting countdown ring." },
    { id: "switchSides", title: "Switch sides", description: "Left then right, with a prompt." },
    { id: "deskMode", title: "Desk breaks", description: "Reminders to stretch while you work." },
    { id: "autoAdvance", title: "Auto-advance", description: "Move to the next stretch automatically." },
    { id: "voice", title: "Voice", description: "Hear each stretch and its cue." },
    { id: "chime", title: "Chime", description: "A soft bell between stretches." },
    { id: "stiffness", title: "Stiffness check-in", description: "Before and after, zero to ten." },
    { id: "history", title: "History", description: "Sessions and how much you loosened." },
    { id: 'band', title: 'Stretch band', description: 'An elastic band lengthens slowly while you hold, a cue to breathe, not bounce.' },
  ],
  runTracker: [
    { id: "gps", title: "GPS tracking", description: "Record your route live." },
    { id: "map", title: "Live map", description: "Your route drawn as you move." },
    { id: "splits", title: "Splits", description: "Time for every kilometre or mile." },
    { id: "paceChart", title: "Pace chart", description: "Bars for each split; fastest glows." },
    { id: "manual", title: "Manual entry", description: "Log with sliders when you had no phone." },
    { id: "bests", title: "Personal bests", description: "Longest, fastest pace, fastest split." },
    { id: "units", title: "Kilometres or miles", description: "Pick your units." },
    { id: "voiceSplits", title: "Voice splits", description: "Hear each split as you pass it." },
    { id: "replay", title: "Route replay", description: "Watch a past route redraw on the map." },
    { id: "weeklyGoal", title: "Weekly goal", description: "A ring for this week’s distance." },
    { id: 'strider', title: 'Moving runner', description: 'A little runner that strides while you move.' },
  ],
  bodyProgress: [
    { id: "measurements", title: "Measurements", description: "Waist, chest, hips, arm, thigh, body fat." },
    { id: "trendLine", title: "Trend lines", description: "A chart that draws itself for each measure." },
    { id: "photos", title: "Progress photos", description: "Kept only on this device." },
    { id: "compare", title: "Before / after", description: "Drag a slider across two photos." },
    { id: "ratios", title: "BMI & waist-to-height", description: "Simple health ratios from your height." },
    { id: "goal", title: "Goal & projection", description: "A goal line and projected date." },
    { id: "privacyBlur", title: "Privacy blur", description: "Photos stay blurred until you reveal them." },
    { id: "checkIn", title: "Weekly reminder", description: "A gentle weekly nudge to check in." },
    { id: "units", title: "Units", description: "Metric or imperial." },
    { id: "smoothing", title: "Trend smoothing", description: "Smooth out daily water-weight noise." },
    { id: 'sparkline', title: 'Weight sparkline', description: 'A trend line that draws itself, with the change toward your goal.' },
  ],
  foodScanner: [
    { id: "camera", title: "Camera scanning", description: "Point your camera at a barcode." },
    { id: "manual", title: "Type a barcode", description: "When the camera can’t read it." },
    { id: "grades", title: "Scores", description: "Nutri-Score, NOVA processing and Eco-Score." },
    { id: "additives", title: "Additives", description: "E-numbers listed plainly." },
    { id: "allergens", title: "Allergen alerts", description: "Warns about the allergens you choose." },
    { id: "sugarCubes", title: "Sugar cubes", description: "See sugar as cubes for your portion." },
    { id: "addToMeal", title: "Add to today", description: "Log a portion straight to Nourish." },
    { id: "history", title: "History & offline", description: "Scanned products are remembered." },
    { id: "compare", title: "Compare", description: "Two products side by side." },
    { id: "productPhoto", title: "Product photo", description: "Show the pack image." },
  ],
  fasting: [
    { id: "protocols", title: "Protocols", description: "14:10, 16:8, 18:6, 20:4, OMAD and 36 h." },
    { id: "ring", title: "Live ring", description: "A glowing ring that fills as you fast." },
    { id: "stages", title: "Body stages", description: "Fed, fat burning, ketosis, autophagy." },
    { id: "adjustStart", title: "Adjust start", description: "Slide back if you began earlier." },
    { id: "heatmap", title: "History heatmap", description: "Months of fasts at a glance." },
    { id: "weeklyAvg", title: "Weekly stats", description: "Average, longest and goals reached." },
    { id: "hydration", title: "Water reminders", description: "Gentle sips while you fast." },
    { id: "endEarly", title: "Kind endings", description: "Ending early still counts." },
    { id: "notes", title: "Feelings & notes", description: "How the fast felt." },
    { id: "windowReminder", title: "Window reminder", description: "When your eating window closes." },
    { id: 'stageTrack', title: 'Stage timeline', description: 'Body stages along a track; a marker glides to where you are.' },
  ],
  focusSounds: [
    { id: "modes", title: "Four modes", description: "Focus, relax, meditate and sleep." },
    { id: "generative", title: "Generative music", description: "Composed live, never the same twice." },
    { id: "neuralPhase", title: "Neural-phase pulsing", description: "Amplitude modulation tuned to each mode’s brainwave band." },
    { id: "intensity", title: "Effect intensity", description: "How strong the pulsing feels." },
    { id: "genres", title: "Genres", description: "Ambient, piano, lo-fi and nature." },
    { id: "binaural", title: "Binaural beats", description: "Optional beats for headphones." },
    { id: "timer", title: "Session timer", description: "Music ends softly when time is up." },
    { id: "visualiser", title: "Visualiser", description: "A living shape that breathes with the music." },
    { id: "fade", title: "Fade in & out", description: "No abrupt starts or stops." },
    { id: "pairFocus", title: "Counts as focus", description: "Finished focus sessions add to your focus minutes." },
  ],
  soundMixer: [
    { id: "natureLayers", title: "Nature layers", description: "Rain, wind, ocean, fire, birds and stream." },
    { id: "noiseColours", title: "Coloured noise", description: "White, pink and brown noise." },
    { id: "organic", title: "Organic motion", description: "Simplex noise drifts every layer so it never loops." },
    { id: "spatial", title: "Spatial drift", description: "Sounds wander gently left and right." },
    { id: "presets", title: "Scenes", description: "Rainy night, beach, campfire, forest, deep focus." },
    { id: "savedMixes", title: "Saved mixes", description: "Keep your favourite blends." },
    { id: "sleepTimer", title: "Sleep timer", description: "Fades out when you drift off." },
    { id: "scene", title: "Living scene", description: "The picture answers your mix." },
    { id: "fade", title: "Soft fades", description: "Gentle starts and stops." },
    { id: "keepPlaying", title: "Plays everywhere", description: "Keeps playing while you use other pages." },
    { id: 'orbit', title: 'Mix orbit', description: 'Active sounds circle the play button, sized by volume.' },
  ],
  meditation: [
    { id: "courses", title: "Courses", description: "Short series for basics, kindness, sleep and focus." },
    { id: "bodyScan", title: "Body scan", description: "Move attention slowly through the body." },
    { id: "kindness", title: "Loving-kindness", description: "Warm wishes for yourself and others." },
    { id: "sos", title: "SOS calm", description: "Three minutes when anxiety spikes." },
    { id: "voice", title: "Spoken guidance", description: "A gentle voice reads each step." },
    { id: "captions", title: "Captions", description: "Guidance appears on screen." },
    { id: "particles", title: "Particle scenes", description: "Stars, fireflies, snow or bubbles." },
    { id: "duration", title: "Length slider", description: "Stretch any session from 3 to 30 minutes." },
    { id: "bells", title: "Interval bells", description: "Soft bells for silent sits." },
    { id: "unguided", title: "Unguided timer", description: "Just you, the scene and a bell." },
    { id: "moodCheck", title: "Calm before & after", description: "See how much each sit helps." },
    { id: 'moodMatch', title: 'Mood match', description: 'Tap how you feel; get the session that fits.' },
    { id: 'swipePick', title: 'Swipe to begin', description: 'Swipe through suggested sessions.' },
  ],
  breathwork: [
    { id: "lungs", title: "Animated lungs", description: "Lungs fill and empty with each breath." },
    { id: "pace", title: "Rounds & pace", description: "Sliders for rounds, breaths and speed." },
    { id: "retention", title: "Retention timer", description: "Time your empty-lung hold." },
    { id: "recovery", title: "Recovery breath", description: "A full hold between rounds." },
    { id: "voice", title: "Voice guidance", description: "Cues for each phase." },
    { id: "tones", title: "Tones", description: "A tone every ten breaths and at each phase." },
    { id: "rounds", title: "Round counter", description: "Breaths left and current round." },
    { id: "keepAwake", title: "Keep screen awake", description: "Your screen stays on during a session." },
    { id: "safety", title: "Safety check", description: "A short note before your first session." },
    { id: "history", title: "Records", description: "Best hold and past sessions." },
    { id: "chart", title: "Retention chart", description: "Bars for each round over time." },
    { id: 'moodPreset', title: 'Mood presets', description: 'A tap on your mood sets rounds, breaths and pace.' },
  ],
  mala: [
    { id: "mala3d", title: "3D mala", description: "A ring of 108 beads that turns as you count; drag to tilt." },
    { id: "library", title: "Mantra library", description: "Traditional and plain-English mantras." },
    { id: "custom", title: "Your mantras", description: "Write your own." },
    { id: "bells", title: "Quarter bells", description: "A chime every 27 beads, a gong at 108." },
    { id: "haptics", title: "Haptics", description: "A tiny tap on each bead." },
    { id: "rounds", title: "Rounds", description: "Count full malas." },
    { id: "themes", title: "Bead themes", description: "Sandalwood, rose, jade and lapis." },
    { id: "autoChant", title: "Auto-count", description: "Counts at a steady pace for you." },
    { id: "chant", title: "Spoken chant", description: "Hear the mantra with each bead." },
    { id: "log", title: "Practice log", description: "Rounds and days practised." },
    { id: 'ripples', title: 'Tap ripples', description: 'Each bead sends a ripple from your fingertip; rounds glow gold.' },
  ],
  inkJournal: [
    { id: "pressure", title: "Pressure-sensitive pen", description: "Lines swell and taper naturally." },
    { id: "colours", title: "Colours", description: "Six ink colours." },
    { id: "highlighter", title: "Highlighter", description: "Soft translucent marker." },
    { id: "eraser", title: "Eraser", description: "Rub out whole strokes." },
    { id: "undo", title: "Undo & redo", description: "Ctrl+Z and Ctrl+Shift+Z work too." },
    { id: "paper", title: "Paper styles", description: "Blank, lined, dotted or grid." },
    { id: "pages", title: "Pages", description: "Keep many pages, saved on this device." },
    { id: "replay", title: "Stroke replay", description: "Watch your page draw itself again." },
    { id: "prompts", title: "Daily prompt", description: "A gentle idea for today’s page." },
    { id: "export", title: "Export PNG", description: "Save a page as an image." },
  ],
  moodMirror: [
    { id: "trend", title: "Tone over time", description: "A line that draws your writing’s mood." },
    { id: "wordCloud", title: "Word clouds", description: "Words that lift you and words that weigh." },
    { id: "weekday", title: "Weekday pattern", description: "Which days read brighter." },
    { id: "compare", title: "Compare with mood", description: "How well your words match the mood you log." },
    { id: "reframes", title: "Gentle reframes", description: "Kind ways to see heavy words." },
    { id: "sources", title: "Sources filter", description: "Journal, Daybook, gratitude or mood notes." },
    { id: "gratitudeWords", title: "Gratitude words", description: "What your thanks is most often about." },
    { id: "privacy", title: "On-device", description: "Nothing is sent anywhere." },
    { id: "weekFace", title: "This week", description: "A face for how this week reads." },
    { id: "scores", title: "Per-entry scores", description: "Every entry scored for tone." },
  ],
  mindMaps: [
    { id: "liveMap", title: "Live map", description: "The map redraws as you type." },
    { id: "templates", title: "Templates", description: "Goals, week plan, decisions, life areas, brain dump." },
    { id: "fromJournal", title: "From a journal page", description: "Turn a Daybook page into a map." },
    { id: "collapse", title: "Collapse & expand", description: "Fold branches to focus." },
    { id: "zoom", title: "Zoom & pan", description: "Scroll to zoom, drag to move, fit in one tap." },
    { id: "colours", title: "Colourful branches", description: "Each level gets its own colour." },
    { id: "saved", title: "Saved maps", description: "Keep as many maps as you like." },
    { id: "export", title: "Export SVG", description: "Save a crisp image of the map." },
    { id: "fullscreen", title: "Full view", description: "Hide the editor for more room." },
    { id: "goalHelper", title: "Goal breakdown", description: "A template for why, milestones and obstacles." },
    { id: 'grow', title: 'Growing branches', description: 'Branches grow in one after another when a map opens.' },
  ],
  flashcards: [
    { id: "decks", title: "Decks", description: "Organise cards by topic." },
    { id: "markdown", title: "Markdown", description: "Bold, lists, code and links on cards." },
    { id: "sm2", title: "Spaced repetition", description: "SM-2 shows each card just before you’d forget." },
    { id: "flip", title: "3D flip", description: "Cards turn over to reveal the answer." },
    { id: "cloze", title: "Cloze deletions", description: "Hide words with {{c1::…}}." },
    { id: "reverse", title: "Reverse cards", description: "Sometimes ask the answer side first." },
    { id: "import", title: "Import", description: "Paste question;answer lines." },
    { id: "dailyLimit", title: "Daily limit", description: "A slider for reviews per day." },
    { id: "tags", title: "Tags", description: "Label cards." },
    { id: "stats", title: "Stats", description: "New, learning, mature and what’s due." },
    { id: 'piles', title: 'Card piles', description: 'Due, learning and known piles; graded cards fly to their pile.' },
  ],
  brainGames: [
    { id: 'chessLessons', title: 'Learn chess', description: 'Guided chess lessons with legal moves and feedback.' },
    { id: 'checkersLessons', title: 'Learn checkers', description: 'Guided lessons for steps, captures and kings.' },
    { id: "nback", title: "N-back", description: "A classic working-memory trainer." },
    { id: "memoryGrid", title: "Memory grid", description: "Recall lit tiles on a growing grid." },
    { id: "stroop", title: "Colour clash", description: "Stroop test for focus." },
    { id: "reaction", title: "Reaction time", description: "How fast you respond." },
    { id: "speedMaths", title: "Speed maths", description: "Mental arithmetic against the clock." },
    { id: "adaptive", title: "Adaptive difficulty", description: "Levels rise and fall with your accuracy." },
    { id: "daily", title: "Daily workout", description: "Three games picked for today." },
    { id: "history", title: "History", description: "Your recent scores." },
    { id: "skillRadar", title: "Skill radar", description: "Memory, attention, speed and maths." },
    { id: "sounds", title: "Sounds", description: "Blips for right and wrong." },
    { id: 'patternEcho', title: 'Pattern echo', description: 'Simon-style sound and colour sequences.' },
    { id: 'rotation3d', title: '3D rotation', description: 'Mental rotation of three.js block shapes.' },
    { id: 'wordScramble', title: 'Word scramble', description: 'Unscramble calm words against the clock.' },
    { id: 'focusTracker', title: 'Focus tracker', description: 'Follow moving dots (multiple-object tracking).' },
    { id: 'numberStream', title: 'Number stream', description: 'Running totals of flashing numbers.' },
    { id: 'personalBest', title: 'Personal-best fireworks', description: 'Fireworks when you beat your best score.' },
    { id: 'assessments', title: 'IQ & EQ assessments', description: 'Reasoning (IQ-style) and emotional intelligence (EQ) check-ins.' },
    { id: 'iqGames', title: 'Reasoning games', description: 'Matrix puzzles and quick analogies to train IQ skills.' },
    { id: 'eqGames', title: 'Empathy games', description: 'Face reader and Kind reply to train EQ skills.' },
    { id: 'leaderboard', title: 'Personal leaderboard', description: 'Your top runs and personal bests, this week or all time.' },
  ],
  goalRoadmap: [
    { id: "timeline", title: "Gantt timeline", description: "Every milestone on one timeline." },
    { id: "dragDates", title: "Drag dates", description: "Move and stretch bars to reschedule." },
    { id: "progress", title: "Drag progress", description: "Slide a bar’s progress handle." },
    { id: "keyResults", title: "Key results", description: "Measurable sliders for each goal." },
    { id: "confidence", title: "Confidence", description: "How sure you feel, out of ten." },
    { id: "views", title: "Week, month, year", description: "Zoom the timeline." },
    { id: "dependencies", title: "Dependencies", description: "Arrows link each milestone to the last." },
    { id: "review", title: "Weekly review", description: "Four questions to steer the goal." },
    { id: "linkTasks", title: "Link to tasks", description: "Send a milestone to your to-dos." },
    { id: "onTrack", title: "On-track check", description: "Compares progress with the time passed." },
  ],
  routineScheduler: [
    { id: "steps", title: "Timed steps", description: "Each step with its own length." },
    { id: "schedule", title: "Recurring schedules", description: "Daily, weekly on chosen days, or monthly." },
    { id: "preview", title: "Plain-language rule", description: "“Every weekday at 07:00.”" },
    { id: "upcoming", title: "Next occurrences", description: "The next five times it’s due." },
    { id: "player", title: "Routine player", description: "One step at a time with a draining timer." },
    { id: "anchors", title: "Habit stacking", description: "Anchor a routine to something you already do." },
    { id: "skip", title: "Skip a day", description: "Pause today without breaking anything." },
    { id: "templates", title: "Templates", description: "Morning, evening, workout and weekly reset." },
    { id: "week", title: "Week view", description: "What’s coming over seven days." },
    { id: "log", title: "Completion log", description: "Streaks from completed runs." },
    { id: 'dial', title: 'Day dial', description: 'Today’s routines on an animated 24-hour clock.' },
  ],
  digitalWellbeing: [
    { id: "tracking", title: "Active time", description: "Counts time you’re actually using Bloom." },
    { id: "hourly", title: "Hourly chart", description: "When in the day you’re on screen." },
    { id: "limit", title: "Daily limit", description: "A ring for your own time budget." },
    { id: "breaks", title: "Break reminders", description: "A calm full-screen pause after long stretches." },
    { id: "detox", title: "Detox mode", description: "Greyscale and still, to make screens less sticky." },
    { id: "windDown", title: "Wind-down dimming", description: "Warmer, dimmer colours in the evening." },
    { id: "pauseGate", title: "Pause before opening", description: "One breath and an intention when Bloom opens." },
    { id: "challenge", title: "Phone-free challenge", description: "Time yourself away from the phone." },
    { id: "focusOnly", title: "Focus-only mode", description: "Hide everything but today’s essentials." },
    { id: "trend", title: "Weekly trend", description: "Seven days against your limit." },
  ],
  eyeCare: [
    { id: "reminders", title: "20-20-20 reminders", description: "A nudge to look far away." },
    { id: "rule20", title: "20-20-20 break", description: "Twenty seconds of distance." },
    { id: "followDot", title: "Follow the dot", description: "Figure eight, circles and zig-zags." },
    { id: "nearFar", title: "Near & far focus", description: "Train your focusing muscles." },
    { id: "blink", title: "Blink training", description: "Relearn relaxed blinking." },
    { id: "palming", title: "Palming", description: "Warm darkness to rest the eyes." },
    { id: "handDrawn", title: "Hand-drawn paths", description: "Sketchy, calming guides." },
    { id: "interval", title: "Reminder interval", description: "A slider for how often." },
    { id: "sounds", title: "Chimes", description: "A soft tone between exercises." },
    { id: "history", title: "History", description: "Breaks taken and your streak." },
    { id: 'watchEye', title: 'Watching eye', description: 'An eye that follows your pointer, blinks and counts down to your next break.' },
  ],
  daylight: [
    { id: "sunArc", title: "Sun arc", description: "A live sky with the sun where it really is." },
    { id: "golden", title: "Golden hour", description: "When the light is softest." },
    { id: "lightGoal", title: "Morning light goal", description: "Minutes outside to anchor your body clock." },
    { id: "caffeine", title: "Caffeine curfew", description: "Your last-coffee time." },
    { id: "windDown", title: "Wind-down window", description: "When to start slowing down." },
    { id: "walk", title: "Best walk time", description: "Before the light fades." },
    { id: "moon", title: "Moon phase", description: "Tonight’s moon." },
    { id: "yearChart", title: "Day length", description: "Daylight through the year." },
    { id: "gps", title: "Use my location", description: "Precise sunrise for where you are." },
    { id: "cities", title: "Cities", description: "Or pick a city." },
  ],
  affirmations: [
    { id: "decks", title: "Themed decks", description: "Calm, confidence, self-kindness, growth and gratitude." },
    { id: "swipe", title: "Swipe cards", description: "A stack you flick through." },
    { id: "favourites", title: "Favourites", description: "Save the ones that land." },
    { id: "custom", title: "Write your own", description: "Your own words in your own deck." },
    { id: "speak", title: "Read aloud", description: "Hear each card spoken." },
    { id: "autoplay", title: "Slideshow", description: "Cards move on by themselves." },
    { id: "repeat", title: "Repeat counter", description: "Say it three times for a sparkle." },
    { id: "themes", title: "Card styles", description: "Gradient, paper or night." },
    { id: "daily", title: "Today’s card", description: "A new card each day." },
    { id: "mix", title: "Mix", description: "Shuffle every deck together." },
    { id: 'moodDeck', title: 'Mood deck', description: 'Tap how you feel; the matching deck opens.' },
  ],
  dojo: [
    { id: "styleFilter", title: "Style filter", description: "Karate, kung fu, taekwondo, boxing, Muay Thai." },
    { id: "seated", title: "Seated dojo", description: "Punches, blocks and strikes from a chair or wheelchair." },
    { id: "forms", title: "Forms", description: "Kata-style sequences with the figure leading." },
    { id: "comboCaller", title: "Combo caller", description: "Random combos called aloud in timed rounds." },
    { id: "belts", title: "Belt progression", description: "White to black belt as you practise." },
    { id: "beltNotation", title: "Hand-drawn belt label", description: "A rough-notation box around your belt." },
    { id: "voice", title: "Voice coach", description: "Calls techniques and counts reps." },
    { id: "southpaw", title: "Southpaw mirror", description: "Flip the figure for left-handed stances." },
    { id: "bell", title: "Round bell", description: "Bell at the start and end of rounds." },
    { id: "safety", title: "Safety notes", description: "Warm-up and stop-if-it-hurts reminders." },
  ],
  pointerFx: [
    { id: "contextMenu", title: "Right-click menu", description: "A menu that changes with each page." },
    { id: "pageShortcuts", title: "Goes well with", description: "Right-click shortcuts to linked features." },
    { id: "selectionActions", title: "Selected text actions", description: "Copy, save as epiphany, make a to-do or search." },
    { id: "shapes", title: "Pointer shapes", description: "Arrow, dot, ink pen, leaf or hand in your colour." },
    { id: "effects", title: "Pointer effects", description: "Follower dot, emoji trail, fairy dust, rainbow, bubbles or snow." },
    { id: "magnetic", title: "Magnetic buttons", description: "The follower sticks to buttons as you pass." },
    { id: "labels", title: "Hover labels", description: "The follower shows hints like Drag or Click." },
    { id: "pageMatch", title: "Match the page", description: "Each page picks its own effect." },
    { id: "bigPointer", title: "Big pointer", description: "Up to 60 px for easier tracking." },
    { id: "menuMotion", title: "Menu animation", description: "Menu items slide in with GSAP." },
    { id: 'emblems', title: 'Animated page emblems', description: 'Each page title has an icon that draws itself and moves.', independent: true },
    { id: 'linkRail', title: 'Works-with links', description: 'One row of related features under each title.', independent: true },
    { id: 'hoverHints', title: 'Hover hints', description: 'A label follows the pointer to explain buttons and items.', independent: true },
    { id: 'gsapControls', title: 'Springy controls', description: 'Buttons, chips and switches squash and spring back when pressed (GSAP).', independent: true },
  ],
  bloomStreet: [
    { id: "walker", title: "Walking sprout", description: "A sprout buddy walks to each building." },
    { id: "drag", title: "Drag the street", description: "Drag or swipe the street sideways." },
    { id: "sky", title: "Drifting clouds", description: "Clouds float across the sky." },
    { id: "lights", title: "Lit windows", description: "Windows glow for places you visited recently." },
    { id: "lamps", title: "Street lamps", description: "Lamps between buildings." },
    { id: "bubble", title: "Name bubble", description: "A speech bubble names the building." },
    { id: "dots", title: "Dot navigation", description: "Dots under the street to jump anywhere." },
    { id: "keys", title: "Arrow keys", description: "Left and right walk, Enter goes in." },
    { id: "menu", title: "Right-click walks", description: "Right-click to go in or walk on." },
    { id: "onlyOn", title: "Only features you use", description: "Buildings for switched-off features are hidden." },
  ],
  moneyTracker: [
    { id: "currency", title: "Currency", description: "Pick the currency Bloom uses for money." },
    { id: "places", title: "Top places", description: "Where you spend the most." },
    { id: "autoCategory", title: "Smart categories", description: "Guess the category from the place." },
    { id: "budgets", title: "Budgets", description: "Monthly limits per category with rings." },
    { id: "flexBuckets", title: "Flex buckets", description: "Fixed, flexible and non-monthly spending." },
    { id: "charts", title: "Charts", description: "Tiles, circles, candles and a year heatmap." },
    { id: "tiles", title: "Day tiles", description: "Last 64 days as coloured number tiles." },
    { id: "circles", title: "Circle packing", description: "Categories and places as packed circles." },
    { id: "candles", title: "Balance candles", description: "Your balance as daily candlesticks." },
    { id: "calendar", title: "Year heatmap", description: "A calendar of spending across the year." },
    { id: "premium", title: "Plan tab", description: "Insights, forecasts, bills, subscriptions, net worth, goals, debt and import." },
    { id: "subscriptions", title: "Subscription finder", description: "Spot repeating payments and their yearly cost." },
    { id: "netWorth", title: "Net worth", description: "Assets minus debts." },
    { id: "goals", title: "Savings goals", description: "Progress towards what you are saving for." },
    { id: "csvImport", title: "CSV import", description: "Bring in a bank statement." },
    { id: 'radar', title: 'Spending shape', description: 'A glowing radar of this month against last month.' },
    { id: 'insights', title: 'Insights', description: 'Plain-language notes on changes and patterns.' },
    { id: 'forecast', title: 'Month-end forecast', description: 'Projected spending from your daily average.' },
    { id: 'noSpend', title: 'No-spend days', description: 'Days without spending and your streak.' },
    { id: 'bills', title: 'Upcoming bills', description: 'Subscriptions due in the next 30 days.' },
    { id: 'debtPlanner', title: 'Debt payoff planner', description: 'Months to debt-free at a chosen payment.' },
  ],
  englishLearning: [
    { id: "storyMode", title: "Story mode", description: "The Word Well: a tournament side quest with Bloom's friends." },
    { id: "hearts", title: "Hearts", description: "Lose a heart for each mistake; they refill over time." },
    { id: "listening", title: "Listening exercises", description: "Hear a sentence and type it." },
    { id: "speaking", title: "Speaking exercises", description: "Say sentences out loud (speech recognition)." },
    { id: "placement", title: "Placement test", description: "Skip ahead to your level." },
    { id: "wordOfDay", title: "Word of the day", description: "A new word every day." },
    { id: "quests", title: "Daily quests", description: "Three quests a day for gems." },
    { id: "review", title: "Practice hub", description: "Spaced review of your words." },
    { id: "mistakes", title: "Mistakes review", description: "Replay what you got wrong." },
    { id: "matchMadness", title: "Match madness", description: "Timed word-matching game." },
    { id: "grammarTips", title: "Grammar tips", description: "Short explanations with examples." },
    { id: "stories", title: "Stories", description: "Short dialogues with questions." },
    { id: "roleplay", title: "Roleplay", description: "Chat through real situations." },
    { id: "pronunciation", title: "Speak lab", description: "Phonemes, stress and syllables." },
    { id: "rhymes", title: "Rhyme time", description: "Find words that rhyme." },
    { id: "minimalPairs", title: "Minimal pairs", description: "Hear the difference: ship or sheep." },
    { id: "spellingBee", title: "Spelling bee", description: "Hear it, spell it." },
    { id: "numbers", title: "Numbers", description: "Write numbers in words." },
    { id: "forms", title: "Plurals & tenses", description: "Irregular plurals and past forms." },
    { id: "writing", title: "Writing coach", description: "Feedback on your English writing." },
    { id: "daybookLink", title: "Daybook practice", description: "Use your Daybook entries as writing practice." },
    { id: "leagues", title: "Leagues", description: "Weekly leagues from Bronze to Diamond." },
    { id: "shop", title: "Gem shop", description: "Streak freezes, heart refills and double XP." },
    { id: "badges", title: "Achievements", description: "Badges for milestones." },
    { id: "charts", title: "Progress chart", description: "XP per day." },
  ],
  littleJoys: [
    { id: "hydration", title: "Hydration", description: "A glass that fills as you drink." },
    { id: "sky", title: "Sky", description: "Moon phase and the sun's path today." },
    { id: "kindness", title: "Kindness deck", description: "One small kind act a day." },
    { id: "moodColours", title: "Mood colours", description: "Breathing colour blobs for your mood." },
    { id: "postcard", title: "Postcard", description: "A shareable card with a QR code." },
    { id: "weekWater", title: "Week of water", description: "Seven-day hydration bars." },
    { id: "goldenHour", title: "Golden hour", description: "When the light is loveliest." },
    { id: "kindStreak", title: "Kindness streak", description: "Days in a row of kindness." },
    { id: "palette", title: "Palette", description: "Copyable colours from your mood." },
    { id: "download", title: "Download postcard", description: "Save your card as SVG." },
  ],
  codeLearning: [
    { id: "storyMode", title: "Code Cup story", description: "A tournament story with videos, rivals and duels." },
    { id: "quiz", title: "Code quiz", description: "Predict the output and concept questions." },
    { id: "challenges", title: "Challenges", description: "Solve problems against hidden tests." },
    { id: "cheatsheets", title: "Cheat sheets", description: "Searchable syntax reminders." },
    { id: "certificate", title: "Certificate", description: "An animated certificate when you finish." },
    { id: "hints", title: "Hints", description: "A nudge when you are stuck." },
    { id: "unstuck", title: "Get unstuck", description: "Show the solution." },
    { id: "drafts", title: "Saved drafts", description: "Your code is kept per lesson." },
    { id: "syntax", title: "Friendly syntax errors", description: "Line numbers and plain messages." },
    { id: "sandbox", title: "Safe sandbox", description: "Code runs in a worker with a time limit." },
    { id: "bloomHints", title: "Bloom hints", description: "Ask Bloom’s chat for a hint." },
  ],
  chessAcademy: [
    { id: "lessons", title: "Piece lessons", description: "Collect stars with each piece." },
    { id: "puzzles", title: "Mate-in-one puzzles", description: "Verified checkmate puzzles." },
    { id: "play", title: "Play Bloom", description: "Three difficulty levels." },
    { id: "hints", title: "Hints", description: "A nudge for each puzzle." },
    { id: "drag", title: "Drag pieces", description: "Drag or tap to move." },
    { id: "tilt", title: "Board tilt", description: "The board leans towards your pointer." },
    { id: "moveList", title: "Move list", description: "Every move in notation." },
    { id: "undo", title: "Undo", description: "Take back a move." },
    { id: "bloomHints", title: "Bloom hints", description: "Ask Bloom’s chat for the answer." },
    { id: "celebrate", title: "Celebrations", description: "Kinetic titles and confetti." },
  ],
  lifeInWeeks: [
    { id: "chapters", title: "Chapters", description: "Colour stretches of life." },
    { id: "milestones", title: "Milestones", description: "Mark special weeks." },
    { id: "counters", title: "Counters", description: "Weeks lived, summers and full moons ahead." },
    { id: "ripple", title: "Ripple reveal", description: "The grid ripples out from now." },
    { id: "hover", title: "Week details", description: "Hover any week for its date and age." },
    { id: "expectancy", title: "Planning horizon", description: "Choose how many years to plan for." },
    { id: "kinetic", title: "Kinetic headline", description: "Sundays left, animated." },
    { id: "privacy", title: "Private", description: "Stored only on this device." },
    { id: "pulse", title: "This week", description: "The current week pulses." },
    { id: "palette", title: "Chapter colours", description: "Harmonious colours per chapter." },
  ],
  nightSky: [
    { id: "planets", title: "Planets", description: "Sun, Moon and five planets." },
    { id: "stars", title: "Bright stars", description: "Forty of the brightest stars." },
    { id: "constellations", title: "Constellations", description: "Five famous star patterns." },
    { id: "starHop", title: "Star-hopping", description: "How to find each pattern." },
    { id: "timeTravel", title: "Time slider", description: "Move the sky ±12 hours." },
    { id: "play", title: "Play", description: "Sweep six hours ahead." },
    { id: "moon", title: "Moon phase", description: "Phase and how much is lit." },
    { id: "location", title: "Your location", description: "Use the device location." },
    { id: "twinkle", title: "Twinkle", description: "Stars shimmer." },
    { id: "labels", title: "Labels", description: "Names on hover." },
  ],
  typingDojo: [
    { id: "lessons", title: "Lessons", description: "Nine lessons from the home row to every letter." },
    { id: "fingers", title: "Finger guide", description: "Each key coloured by its finger." },
    { id: "glow", title: "Next key glow", description: "The next key pulses." },
    { id: "realWords", title: "Real words", description: "Drills use real English words." },
    { id: "wpm", title: "Speed", description: "Words per minute." },
    { id: "accuracy", title: "Accuracy", description: "Mistakes are counted and shown." },
    { id: "chart", title: "Progress chart", description: "WPM over your sessions." },
    { id: "best", title: "Personal best", description: "Best speed per lesson." },
    { id: "glide", title: "Gliding line", description: "The text slides as you type." },
    { id: "celebrate", title: "Celebrations", description: "Confetti when you finish." },
  ],
  pianoTrainer: [
    { id: "play", title: "Free play", description: "Play with mouse, touch or keyboard." },
    { id: "quest", title: "Note quest", description: "Find the note on the keys." },
    { id: "intervals", title: "Intervals", description: "Name the gap between two notes." },
    { id: "chords", title: "Chords", description: "Major, minor and more by ear." },
    { id: "songs", title: "Songs", description: "Follow falling notes." },
    { id: "mnemonics", title: "Song mnemonics", description: "Remember intervals by famous tunes." },
    { id: "keyboard", title: "Computer keys", description: "Play from your keyboard." },
    { id: "colours", title: "Pitch colours", description: "Each note has its own colour." },
    { id: "ripples", title: "Ripples", description: "Keys ripple when pressed." },
    { id: "bloomHints", title: "Bloom hints", description: "Ask Bloom for an ear-training hint." },
  ],
  tuner: [
    { id: "mic", title: "Microphone tuner", description: "Live pitch from your mic." },
    { id: "gauge", title: "Gauge", description: "A springy needle in cents." },
    { id: "presets", title: "Instruments", description: "Guitar, ukulele, bass and voice." },
    { id: "reference", title: "Reference tones", description: "Hear each string's note." },
    { id: "closest", title: "Closest string", description: "Highlights the string you are tuning." },
    { id: "inTune", title: "In-tune ring", description: "A ring bursts when you hit it." },
    { id: "clarity", title: "Clarity", description: "How clean the signal is." },
    { id: "frequency", title: "Frequency", description: "Hertz and cents." },
    { id: "idle", title: "Idle sweep", description: "The needle breathes before you start." },
    { id: "private", title: "Private", description: "Audio never leaves the device." },
  ],
  signAlphabet: [
    { id: "learn", title: "Learn letters", description: "An animated hand for each letter." },
    { id: "quiz", title: "Quiz", description: "Name the hand shape." },
    { id: "camera", title: "Camera practice", description: "Hand tracking on your device." },
    { id: "hold", title: "Hold to sign", description: "A ring fills as you hold a letter." },
    { id: "skeleton", title: "Hand skeleton", description: "See the tracked points." },
    { id: "words", title: "Words", description: "Spell real words." },
    { id: "scoring", title: "Scoring", description: "Letters right, by edit distance." },
    { id: "undo", title: "Undo", description: "Remove the last letter." },
    { id: "private", title: "Private", description: "Nothing is recorded or uploaded." },
    { id: "bloomHints", title: "Bloom hints", description: "Ask Bloom for the answer in the quiz." },
  ],
  globeQuiz: [
    { id: "find", title: "Find it", description: "Click the country on the globe." },
    { id: "name", title: "Name it", description: "Type the glowing country." },
    { id: "capitals", title: "Capitals", description: "Pick the capital." },
    { id: "continents", title: "Continents", description: "Focus on one continent." },
    { id: "spin", title: "Spin to answer", description: "The globe glides to each country." },
    { id: "drag", title: "Drag to spin", description: "Turn the globe yourself." },
    { id: "idle", title: "Idle rotation", description: "A slow spin while you think." },
    { id: "fuzzy", title: "Forgiving answers", description: "Small typos are fine." },
    { id: "score", title: "Score", description: "Right answers this session." },
    { id: "bloomHints", title: "Bloom hints", description: "Ask Bloom for help." },
  ],
  cprCoach: [
    { id: "metronome", title: "Compression metronome", description: "110 per minute with a click." },
    { id: "chest", title: "Animated chest", description: "Hands press, the heart pulses." },
    { id: "breaths", title: "30:2 mode", description: "Rescue-breath pauses for trained rescuers." },
    { id: "tapAlong", title: "Tap along", description: "Measure your own rhythm." },
    { id: "gauge", title: "Rhythm gauge", description: "Faster or slower at a glance." },
    { id: "steps", title: "DRSABCD", description: "The life-support steps." },
    { id: "cards", title: "First-aid cards", description: "Choking, bleeding, burns, stroke, recovery, AED." },
    { id: "awake", title: "Screen stays on", description: "The screen won’t sleep during practice." },
    { id: "disclaimer", title: "Training aid", description: "Not a substitute for a course." },
    { id: "celebrate", title: "Celebrations", description: "A burst for a steady rhythm." },
  ],
  speedReader: [
    { id: "rsvp", title: "One word at a time", description: "RSVP reading." },
    { id: "focal", title: "Focal letter", description: "The anchor letter stays centred." },
    { id: "speed", title: "Speed", description: "150–900 words per minute." },
    { id: "pacing", title: "Smart pacing", description: "Pauses at commas and full stops." },
    { id: "texts", title: "Built-in texts", description: "Three short reads." },
    { id: "paste", title: "Your own text", description: "Paste anything." },
    { id: "quiz", title: "Comprehension check", description: "Auto-generated questions." },
    { id: "effective", title: "Effective speed", description: "Speed × understanding." },
    { id: "chart", title: "Progress chart", description: "Your speed over time." },
    { id: "space", title: "Space to pause", description: "Keyboard control." },
  ],
  decisionLab: [
    { id: "matrix", title: "Decision matrix", description: "Score options against what matters." },
    { id: "weights", title: "Weights", description: "How much each thing matters." },
    { id: "bars", title: "Racing bars", description: "Results animate as you score." },
    { id: "coin", title: "3D coin", description: "A gut-check flip." },
    { id: "feelings", title: "Feelings check", description: "Notice relief or disappointment." },
    { id: "regret", title: "10/10/10", description: "The long-view test." },
    { id: "typed", title: "Typed scores", description: "Type a score, even 3+1." },
    { id: "options", title: "Up to four options", description: "Compare more than two." },
    { id: "strongest", title: "Strongest reason", description: "Where the leader wins." },
    { id: "private", title: "Private", description: "Saved on this device." },
  ],
  peopleGarden: [
    { id: "plants", title: "Plants", description: "Each person is a plant." },
    { id: "health", title: "Health", description: "Plants droop as time passes." },
    { id: "water", title: "We talked", description: "Water a plant when you connect." },
    { id: "rhythms", title: "Rhythms", description: "Weekly to every season." },
    { id: "suggestions", title: "Reach out today", description: "Who is overdue." },
    { id: "birthdays", title: "Birthdays", description: "Upcoming birthdays." },
    { id: "calendar", title: "Calendar export", description: "Birthdays as an .ics file." },
    { id: "notes", title: "Notes", description: "Things to remember." },
    { id: "search", title: "Search", description: "Find someone quickly." },
    { id: "sway", title: "Sway", description: "Plants sway gently." },
  ],
  bloomCore: [
    { id: 'nowCard', title: 'What to do now', description: 'One obvious next action that changes with the time of day.' },
    { id: 'simpleHome', title: 'Simple home', description: 'Fewer choices on the dashboard; the rest is one tap away.' },
    { id: 'growth', title: 'Bloom Growth', description: 'Seed → Sprout → Growing → Thriving → Blooming, from real progress.' },
    { id: 'pillars', title: 'Weekly balance', description: 'Do, Focus, Reflect and Care bars.' },
    { id: 'progress', title: 'Progress rings', description: 'Habits, today’s plan and focus minutes at a glance.' },
    { id: 'recognition', title: 'Human recognition', description: 'Personal acknowledgement instead of “+XP”.' },
    { id: 'discoveries', title: 'Discoveries', description: 'Meaningful actions sometimes reveal a pattern about you.' },
    { id: 'dayComplete', title: 'Day complete', description: 'A moment when everything you planned is done.' },
    { id: 'weekly', title: 'Sunday story', description: 'Reveal what changed this week.' },
    { id: 'welcomeBack', title: 'Welcome back', description: 'Return to where you left off, never to a broken streak.' },
    { id: 'tomorrowSeed', title: 'Daily seed', description: 'A new question each day and tomorrow’s bud in your garden.' },
    { id: 'onboarding', title: 'Quick start', description: 'Goal → routine → first task, in under a minute.' },
    { id: 'celebration', title: 'Celebration effects', description: 'Petals, chime and haptics in big moments.' },
  ],
  epiphanies: [
    { id: 'obstruct', title: 'Review before habits', description: 'Due insights cover your habits until graded.' },
    { id: 'recallFirst', title: 'Recall first', description: 'Hide the text until you try to remember it.' },
    { id: 'curve', title: 'Forgetting curve', description: 'See how recall fades until the next review.' },
    { id: 'extract', title: 'Extract from Daybook', description: 'Save a highlighted sentence as an epiphany.' },
    { id: 'capsule', title: 'In the Time capsule', description: 'Epiphanies can resurface as memories.' },
    { id: 'swipeReview', title: 'Swipe review', description: 'Right if you remembered, left if you forgot.' },
    { id: 'bulbGlow', title: 'Glowing bulb', description: 'The bulb brightens as you remember more.' },
    { id: 'moodLift', title: 'Mood lift', description: 'Low days show uplifting insights first.' },
    { id: 'dailyPick', title: 'Insight of the day', description: 'One epiphany pinned each day.' },
    { id: 'reviewStreak', title: 'Review streak', description: 'Days in a row you reviewed.' },
    { id: 'garland', title: 'Lightbulb garland', description: 'Insights hang as bulbs that glow as brightly as you remember them.' },
  ],
  dailyFlow: [
    { id: 'morning', title: 'Morning setup', description: 'Insight, check-in, intention, habit, focus.' },
    { id: 'evening', title: 'Evening wind-down', description: 'Gratitude, reflection, breath, tomorrow, sleep.' },
    { id: 'autoSwitch', title: 'Follow the clock', description: 'Show morning or evening by time of day.' },
    { id: 'ring', title: 'Progress ring', description: 'Animated ring for the routine.' },
    { id: 'suggestions', title: 'Next-step nudges', description: 'Suggestions that link features after you act.', independent: true },
  ],
  postureGuard: [
    { id: 'warnings', title: 'Slouch warnings', description: 'A warning after 5 minutes of slouching.' },
    { id: 'poison', title: 'Poison damage', description: 'Ignored warnings cost HP.' },
    { id: 'stamina', title: 'Stamina buff', description: 'Good posture restores HP.' },
    { id: 'preview', title: 'Camera preview', description: 'See yourself on the posture page.' },
    { id: 'skeleton', title: 'Pose skeleton', description: 'Lines over shoulders and neck.' },
    { id: 'tuning', title: 'Tuning controls', description: 'Timing, sensitivity and damage.' },
  ],
}

let cache: { raw: string | null; sub: Record<string, boolean>; features: Record<string, boolean> } | null = null
function read() {
  let raw: string | null = null
  try {
    raw = localStorage.getItem(SETTINGS_STORAGE_KEY)
  } catch {
    /* storage unavailable */
  }
  if (!cache || cache.raw !== raw) {
    let parsed: { sub?: Record<string, boolean>; features?: Record<string, boolean> }
    try {
      parsed = raw ? JSON.parse(raw) : {}
    } catch {
      parsed = {}
    }
    cache = { raw, sub: parsed.sub ?? {}, features: parsed.features ?? {} }
  }
  return cache
}

/** True unless the user switched this option (or its parent feature) off. */
export function subOn(feature: keyof FeatureFlags, id: string, options?: { ignoreParent?: boolean }) {
  const { sub, features } = read()
  const independent = options?.ignoreParent || subFeatures[feature]?.some((o) => o.id === id && o.independent)
  if (!independent && features[feature] === false) return false
  return sub[`${feature}.${id}`] !== false
}

/**
 * Options for everyday pages that are always on (they have no main switch).
 * Stored as `sub["page.<page>.<option>"]`, missing = on.
 */
export const pageOptions: Record<string, { title: string; emoji: string; options: SubFeature[] }> = {
  todos: {
    title: 'To-dos',
    emoji: '✅',
    options: [
      { id: 'naturalAdd', title: 'Natural quick-add', description: 'Type dates, !priority and #tags in plain words.' },
      { id: 'moodMatch', title: 'Energy match', description: 'Pick a mood, get tasks that fit it.' },
      { id: 'triage', title: 'Swipe triage', description: 'Swipe overdue tasks to today or later.' },
      { id: 'somedayOnNo', title: 'Someday list', description: 'Old tasks swiped left go to #someday.' },
    ],
  },
  intentions: {
    title: 'Intentions',
    emoji: '🌅',
    options: [
      { id: 'templateSwipe', title: 'Swipe intentions', description: 'Swipe right on ready-made intentions until you have three.' },
      { id: 'moodTemplates', title: 'Mood ideas', description: 'Templates that suit how you feel come first.' },
    ],
  },
  focus: {
    title: 'Focus timer',
    emoji: '⏱️',
    options: [
      { id: 'moodLength', title: 'Mood-sized sessions', description: 'Pick your energy; the session length follows.' },
      { id: 'taskSwipe', title: 'Swipe a task', description: 'Swipe right on the task to focus on.' },
      { id: 'growScenes', title: 'Grow scenes', description: 'Tree, flower bed, city, treasure, reef or space station.' },
      { id: 'sceneScale', title: 'Scenes that scale', description: 'Each session today makes the next scene bigger.' },
      { id: 'diorama', title: 'Week diorama', description: 'Every session this week as a little grown scene on a shelf.' },
    ],
  },
}
export function pageOn(page: keyof typeof pageOptions, id: string) {
  return read().sub[`page.${page}.${id}`] !== false
}
