import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('bloom-welcome-v1', '{}'))
})

test('guide suggestions show three at a time and slider reveals remaining actions', async ({ page }, testInfo) => {
  await page.goto('/#games')
  await page.getByRole('button', { name: 'Talk to Bloom', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Talk to Bloom', exact: true })
  const choices = panel.getByRole('group', { name: 'Choices', exact: true })
  await expect(choices.getByRole('button')).toHaveCount(3)
  await expect(choices.getByRole('button', { name: 'Show my leaderboard' })).toHaveCount(0)
  const slider = choices.getByRole('slider')
  await slider.focus()
  await slider.press('ArrowRight')
  await expect(choices.getByRole('button', { name: 'Show my leaderboard' })).toBeVisible()
  await expect(choices.getByRole('button')).toHaveCount(3)
  await expect(slider).toHaveAttribute('aria-valuetext', /Page 2 of/)
  expect(await panel.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('bloom-slider.png') })
})

test('draft recovers after refresh and guide transcript can be downloaded', async ({ page }) => {
  await page.goto('/#focus')
  await page.getByRole('button', { name: 'Talk to Bloom', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Talk to Bloom', exact: true })
  const input = panel.getByRole('searchbox')
  await input.fill('help')
  await page.reload()
  if (!(await panel.isVisible())) await page.getByRole('button', { name: 'Talk to Bloom', exact: true }).click()
  await expect(input).toHaveValue('help')
  await input.press('Enter')
  await expect(input).toHaveValue('')
  await expect(panel.getByText('help', { exact: true })).toBeVisible()
  await panel.getByText('Conversation tools', { exact: true }).click()
  const download = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export conversation', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/^bloom-guide-.*\.txt$/)
})

test('planning suggestions page and the most recent prompt can be edited', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Talk to Bloom', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Talk to Bloom', exact: true })
  await panel.getByRole('tab', { name: 'Plan with Bloom', exact: true }).click()
  const prompts = panel.getByRole('group', { name: 'Planning prompts' })
  await expect(prompts.getByRole('button')).toHaveCount(3)
  await prompts.getByRole('slider').focus()
  await prompts.getByRole('slider').press('ArrowRight')
  await prompts.getByRole('button', { name: 'I have 15 minutes', exact: true }).click()
  await expect(panel.getByRole('heading', { name: 'Your next small steps' })).toBeVisible()
  await panel.getByText('Conversation tools', { exact: true }).click()
  await panel.getByRole('button', { name: 'Edit last prompt', exact: true }).click()
  await expect(panel.getByLabel('Message Bloom', { exact: true })).toHaveValue('I have 15 minutes')
  await expect(panel.getByLabel('Message Bloom', { exact: true })).toBeFocused()
})

test('mobile chat fills the viewport and restores page scrolling on close', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Dedicated mobile behavior')
  await page.goto('/')
  await page.getByRole('button', { name: 'Talk to Bloom', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Talk to Bloom', exact: true })
  const bounds = await panel.boundingBox()
  expect(bounds?.x).toBe(0)
  expect(bounds?.y).toBe(0)
  expect(bounds?.width).toBe(390)
  expect(bounds?.height).toBe(844)
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
  await panel.getByRole('button', { name: 'Close Bloom', exact: true }).click()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
  await expect(page.getByRole('button', { name: 'Talk to Bloom', exact: true })).toBeFocused()
})
