import { useState, type Dispatch, type SetStateAction } from 'react'
import { COLOR_TOKENS, safeColors, type ThemeSettings } from '../utils/themeEngine'

type ThemePack = { id: string; name: string; author: string; colors: Record<string, string> }
const KEY = 'bloom-theme-marketplace-v1'
function load(): ThemePack[] { try { const value: unknown = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(value) ? value.filter(isPack).slice(0, 100) : [] } catch { return [] } }
function isPack(value: unknown): value is ThemePack { if (!value || typeof value !== 'object') return false; const pack = value as Partial<ThemePack>; return typeof pack.id === 'string' && typeof pack.name === 'string' && typeof pack.author === 'string' && !!pack.colors && Object.keys(safeColors(pack.colors)).length > 0 }
function parsePack(text: string): ThemePack { const value: unknown = JSON.parse(text); if (!value || typeof value !== 'object') throw Error('Expected a theme JSON object.'); const pack = value as Partial<ThemePack>; const colors = safeColors(pack.colors); if (!pack.name || typeof pack.name !== 'string' || !Object.keys(colors).length) throw Error('Add a name and at least one valid hex color in colors.'); return { id: crypto.randomUUID(), name: pack.name.slice(0, 80), author: typeof pack.author === 'string' ? pack.author.slice(0, 80) : 'Community', colors } }

export function ThemeMarketplace({ theme, setTheme }: { theme: ThemeSettings; setTheme: Dispatch<SetStateAction<ThemeSettings>> }) {
  const [packs, setPacks] = useState(load)
  const [draft, setDraft] = useState(() => JSON.stringify({ name: 'My Bloom theme', author: 'Me', colors: { '--bg-primary': '#fbf6f1', '--bg-surface': '#fffdfb', '--text-primary': '#30251f', '--accent-color': '#d0643f' } }, null, 2))
  const [message, setMessage] = useState('')
  const save = (next: ThemePack[]) => { setPacks(next); try { localStorage.setItem(KEY, JSON.stringify(next)) } catch { setMessage('Storage is unavailable; this theme will last only for this session.') } }
  const add = (text: string) => { try { const pack = parsePack(text); save([...packs, pack]); setMessage(`Added ${pack.name}.`); return pack } catch (error) { setMessage(error instanceof Error ? error.message : 'Invalid JSON.'); return null } }
  const download = (pack: ThemePack) => { const blob = new Blob([JSON.stringify({ name: pack.name, author: pack.author, colors: pack.colors }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${pack.name.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  return <section aria-labelledby="marketplace-heading" style={{ marginBlock: 24 }}><h2 id="marketplace-heading">Theme marketplace</h2><p>Share a JSON file with another Bloom user, or import one they shared with you. Themes are saved on this device.</p>
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBlock: 12 }}><label>Import theme JSON <input type="file" accept=".json,application/json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 100_000) { setMessage('Choose a JSON file under 100 KB.'); return } add(await file.text()); event.target.value = '' }} /></label><button type="button" onClick={() => setTheme((current) => ({ ...current, customColors: {} }))}>Clear color overrides</button></div>
    <label htmlFor="theme-json-editor">Edit theme properties in JSON</label><p><small>Supported colors: {COLOR_TOKENS.join(', ')}. Use #RGB or #RRGGBB.</small></p><textarea id="theme-json-editor" spellCheck={false} value={draft} onChange={(event) => setDraft(event.target.value)} rows={10} style={{ width: '100%', maxWidth: 700, fontFamily: 'monospace' }} /><div><button type="button" onClick={() => { const pack = add(draft); if (pack) setTheme((current) => ({ ...current, customColors: pack.colors })) }}>Save and apply JSON</button></div>
    {message && <p role="status">{message}</p>}
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 12, marginBlock: 16 }}>{packs.map((pack) => <article key={pack.id} style={{ padding: 12, border: '1px solid var(--border-color,#aaa6)', borderRadius: 10, background: 'var(--bg-surface)' }}><div style={{ display: 'flex', gap: 4 }}>{Object.values(pack.colors).slice(0, 5).map((color, index) => <span key={index} style={{ background: color, width: 22, height: 22, borderRadius: '50%', border: '1px solid #8886' }} />)}</div><h3>{pack.name}</h3><p>by {pack.author}</p><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><button type="button" onClick={() => setTheme((current) => ({ ...current, customColors: pack.colors }))}>Apply</button><button type="button" onClick={() => download(pack)}>Export</button><button type="button" onClick={() => save(packs.filter((item) => item.id !== pack.id))}>Delete</button></div></article>)}</div>
    {packs.length === 0 && <p>No imported themes yet.</p>}
    <small>{Object.keys(safeColors(theme.customColors)).length} custom color properties active.</small>
  </section>
}
