export const cars = [
  {
    id: 'mint-mile',
    name: 'Mint Mile',
    kind: 'City hatch',
    effect: 'bounce',
    color: '#55b99c',
    light: '#a7ead0',
    accent: '#ffe99c',
    body: 'hatch',
  },
  {
    id: 'cherry-shift',
    name: 'Cherry Shift',
    kind: 'Rally coupe',
    effect: 'dash',
    color: '#de5269',
    light: '#ff9ba4',
    accent: '#fff2d2',
    body: 'coupe',
  },
  {
    id: 'sunbeam',
    name: 'Sunbeam',
    kind: 'Weekend camper',
    effect: 'sunshine',
    color: '#e8b548',
    light: '#ffe19a',
    accent: '#559ca3',
    body: 'van',
  },
  {
    id: 'moon-taxi',
    name: 'Moon Taxi',
    kind: 'Lunar hovercar',
    effect: 'hover',
    color: '#c4cdd9',
    light: '#f3f6fa',
    accent: '#66dced',
    body: 'hover',
  },
  {
    id: 'violet-hour',
    name: 'Violet Hour',
    kind: 'Night racer',
    effect: 'neon',
    color: '#9374c4',
    light: '#ceb3f4',
    accent: '#f6a3d9',
    body: 'racer',
  },
  {
    id: 'coast-runner',
    name: 'Coast Runner',
    kind: 'Surf wagon',
    effect: 'cruise',
    color: '#478ebf',
    light: '#8bc8ed',
    accent: '#f5d88e',
    body: 'wagon',
  },
] as const

export type Car = (typeof cars)[number]
export const findCar = (id: string | null) => cars.find((car) => car.id === id)
